root: true
extends: 
  - airbnb
  - airbnb/hooks
parserOptions:
  sourceType: module
  ecmaVersion: 13
plugins:
  - jest
env: 
  "jest": true
rules:
  brace-style:
    - error
    - stroustrup
  react/react-in-jsx-scope:
    off